name: Deploy Laravel to Hostinger via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Assets
        run: NODE_OPTIONS=--max-old-space-size=4096 npm run build

      # ========================================================================
      # CORREÇÃO DEFINITIVA: Deploy via Rsync com Chave SSH
      # ========================================================================
      - name: Deploy Application files
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SERVER_SSH_PORT }}
          SOURCE: "/" # A raiz do projeto no runner
          TARGET: "~/domains/tumulos.xyz/laravel_app/"
          EXCLUDE: "/public/, /node_modules/, /.git/, /.github/"

      - name: Deploy Public folder
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SERVER_SSH_PORT }}
          SOURCE: "public/"
          TARGET: "~/domains/tumulos.xyz/public_html/"
      # ========================================================================

      - name: Run Final Commands on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }} # ssh-action ainda pode usar senha para comandos
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd ~/domains/tumulos.xyz/laravel_app
            php artisan migrate --force
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            echo "Deployment finished successfully!"